name: Clean packages
on:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo -${{ github.event.registry_package.package_version.package_files.length }}- -${{ github.event.registry_package.package_version.package_files[0].name }}-

#      - name: Clean
#        uses: actions/delete-package-versions@v4
#        with:
#          package-type: maven
#          ignore-versions: '^((?!SNAPSHOT).)*$'
