name: Clean packages
on:
  registry_package:
    types: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo ${{ github.event.registry_package.name }} ${{ github.event.registry_package.namespace }} ${{ github.event.registry_package.package_type }}
