name: Clean packages
on:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo -${{ github.event.registry_package.registry.name }}- -${{ github.event.registry_package.registry.type }}-
