name: Clean packages
on:
  registry_package:
    types: [updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo -${{ github.event.registry_package.package_version.summary }}- -${{ github.event.registry_package.package_version.name }}- -${{ github.event.registry_package.package_version.summary }}-

#      - name: Clean
#        uses: actions/delete-package-versions@v4
#        with:
#          package-type: maven
#          ignore-versions: '^((?!SNAPSHOT).)*$'
